// =====================================================================
// DEPTH NORMALS PASS (Auto-generated by FreeSkies)
// =====================================================================
Pass
{
    Name "DepthNormals"
    Tags { "LightMode" = "DepthNormals" }
    ZWrite On
    Cull Back

    HLSLPROGRAM
    #pragma target 4.5
    {{TESSELLATION_PRAGMAS}}
    {{VERTEX_PRAGMA}}
    #pragma fragment DepthNormalsFragment
    
    #pragma multi_compile_instancing
    #pragma multi_compile _ DOTS_INSTANCING_ON
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}


    // -------------------------------------------------------------------------
    // Shared body from MainPass
    // -------------------------------------------------------------------------
    {{FORWARD_CONTENT}}    

    
    // -------------------------------------------------------------------------
    // Hook Functions
    // -------------------------------------------------------------------------
    {{HOOK_DEFINES}}
    {{HOOK_FUNCTIONS}}
    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    DepthNormalsInterpolators DepthNormalsVertex(DepthNormalsAttributes input)
    {
        DepthNormalsInterpolators output = (DepthNormalsInterpolators)0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        // Hook: vertex displacement
        {{VERTEX_DISPLACEMENT_CALL}}
        
        output.{{SV_POSITION}} = TransformObjectToHClip(input.{{POSITION}}.xyz);
        output.{{NORMAL_WS}} = TransformObjectToWorldNormal(input.{{NORMAL}});
        
        // Hook: transfer extra interpolators
        {{INTERPOLATOR_TRANSFER_CALL}}
        
        return output;
    }
    
    // -------------------------------------------------------------------------
    // Tessellation
    // -------------------------------------------------------------------------
    {{TESSELLATION_CODE}}


    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 DepthNormalsFragment(DepthNormalsInterpolators input) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        // Hook: alpha clipping
        {{ALPHA_CLIP_CALL}}
        
        return half4(normalize(input.{{NORMAL_WS}}) * 0.5 + 0.5, input.{{SV_POSITION}}.z);
    }
    ENDHLSL
}
