// =====================================================================
// DEPTH ONLY PASS (Auto-generated by FreeSkies)
// =====================================================================
Pass
{
    Name "DepthOnly"
    Tags { "LightMode" = "DepthOnly" }
    ZWrite On
    ColorMask R
    Cull Back

    HLSLPROGRAM
    #pragma target 4.5
    {{TESSELLATION_PRAGMAS}}
    {{VERTEX_PRAGMA}}
    #pragma fragment DepthOnlyFragment
    
    #pragma multi_compile_instancing
    #pragma multi_compile _ DOTS_INSTANCING_ON
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    
    {{FORWARD_CONTENT}}
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}
    
    // -------------------------------------------------------------------------
    // Hook Functions
    // -------------------------------------------------------------------------
    {{HOOK_DEFINES}}
    {{HOOK_FUNCTIONS}}
    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    DepthOnlyInterpolators DepthOnlyVertex(DepthOnlyAttributes input)
    {
        DepthOnlyInterpolators output = (DepthOnlyInterpolators)0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        // Hook: vertex displacement
        {{VERTEX_DISPLACEMENT_CALL}}
        
        output.{{SV_POSITION}} = TransformObjectToHClip(input.{{POSITION}}.xyz);
        output.{{TEXCOORD0}} = input.{{TEXCOORD0}};
        
        // Hook: transfer extra interpolators
        {{INTERPOLATOR_TRANSFER_CALL}}
        
        return output;
    }

    // -------------------------------------------------------------------------
    // Tessellation
    // -------------------------------------------------------------------------
    {{TESSELLATION_CODE}}
    
    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 DepthOnlyFragment(DepthOnlyInterpolators input) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        // Hook: alpha clipping
        {{ALPHA_CLIP_CALL}}
        
        return input.{{SV_POSITION}}.z;
    }
    ENDHLSL
}
