// =====================================================================
// META PASS (Auto-generated by FreeSkies)
// Used for lightmap baking and GI
// =====================================================================
Pass
{
    Name "Meta"
    Tags { "LightMode" = "Meta" }
    Cull Off

    HLSLPROGRAM
    #pragma target 4.5
    #pragma vertex MetaPassVertex
    #pragma fragment MetaPassFragment
    
    #pragma multi_compile_instancing
    #pragma multi_compile _ EDITOR_VISUALIZATION
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/MetaInput.hlsl"
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}

    // -------------------------------------------------------------------------
    // Shared body from MainPass
    // -------------------------------------------------------------------------
    {{FORWARD_CONTENT}}    

    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    MetaInterpolators MetaPassVertex(MetaAttributes input)
    {
        MetaInterpolators output = (MetaInterpolators)0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        output.{{SV_POSITION}} = UnityMetaVertexPosition(input.{{POSITION}}.xyz, input.uv1, input.uv2, unity_LightmapST, unity_DynamicLightmapST);
        
        return output;
    }

    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 MetaPassFragment(MetaInterpolators input) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        // Sample base color for meta pass (lightmap baking)
        // TODO: Sample _BaseMap if available
        half4 albedo = half4(1, 1, 1, 1);
        
        MetaInput metaInput = (MetaInput)0;
        metaInput.Albedo = albedo.rgb;
        metaInput.Emission = half3(0, 0, 0);
        //metaInput.SpecularColor = half3(0, 0, 0);
        
        return UnityMetaFragment(metaInput);
    }
    ENDHLSL
}
