// =====================================================================
// MOTION VECTORS PASS (Auto-generated by FreeSkies)
// =====================================================================
Pass
{
    Name "MotionVectors"
    Tags { "LightMode" = "MotionVectors" }
    ColorMask RG
    Cull Back

    HLSLPROGRAM
    #pragma target 4.5
    {{TESSELLATION_PRAGMAS}}
    {{VERTEX_PRAGMA}}
    #pragma fragment MotionVectorsFragment
    
    #pragma multi_compile _ _ADD_PRECOMPUTED_VELOCITY
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/MotionVectorsCommon.hlsl"
    
    // -------------------------------------------------------------------------
    // Preprocessor from MainPass (includes, defines, keywords)
    // -------------------------------------------------------------------------
    {{FORWARD_PREPROCESSOR}}
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}

    // -------------------------------------------------------------------------
    // Helper functions from MainPass
    // -------------------------------------------------------------------------
    {{FORWARD_CONTENT}}    

    
    // -------------------------------------------------------------------------
    // Hook Functions
    // -------------------------------------------------------------------------
    {{HOOK_DEFINES}}
    {{HOOK_FUNCTIONS}}
    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    {{INTERPOLATORS_NAME}} MotionVectorsVertex({{ATTRIBUTES_NAME}} input)
    {
        {{INTERPOLATORS_NAME}} output = ({{INTERPOLATORS_NAME}})0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        // Store original position for previous frame calculation
        float3 originalPosOS = input.{{POSITION}}.xyz;
        
        // Hook: vertex displacement (current frame)
        {{VERTEX_DISPLACEMENT_CALL}}
        
        // Injected forward vertex body (interpolator transfers)
        {{FORWARD_VERTEX_BODY}}
        
        // Current position (after displacement)
        float3 positionWS = TransformObjectToWorld(input.{{POSITION}}.xyz);
        output.{{SV_POSITION}} = TransformWorldToHClip(positionWS);
        output.curPositionCS = mul(_NonJitteredViewProjMatrix, float4(positionWS, 1.0));
        
        // Previous position calculation
        float3 prevPosOS = (unity_MotionVectorsParams.x == 1) ? input.positionOld : originalPosOS;
        
        #if defined(_ADD_PRECOMPUTED_VELOCITY)
            prevPosOS -= input.alembic;
        #endif
        
        // Apply displacement to previous position with time offset
        #ifdef FS_VERTEX_DISPLACEMENT
            // Temporarily offset time for previous frame displacement
            float4 savedPosition = input.{{POSITION}};
            input.{{POSITION}} = float4(prevPosOS, 1.0);
            
            // Note: For accurate motion vectors with animated displacement,
            // the displacement function should use _Time. We offset it here.
            // This is a simplified approach - complex cases may need custom handling.
            {{VERTEX_DISPLACEMENT_CALL}}
            
            prevPosOS = input.{{POSITION}}.xyz;
            input.{{POSITION}} = savedPosition;
        #endif
        
        float3 prevPositionWS = mul(UNITY_PREV_MATRIX_M, float4(prevPosOS, 1.0)).xyz;
        output.prevPositionCS = mul(_PrevViewProjMatrix, float4(prevPositionWS, 1.0));
        
        // Hook: transfer extra interpolators
        {{INTERPOLATOR_TRANSFER_CALL}}
        
        return output;
    }

    // -------------------------------------------------------------------------
    // Tessellation
    // -------------------------------------------------------------------------
    {{TESSELLATION_CODE}}

    
    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 MotionVectorsFragment({{INTERPOLATORS_NAME}} input{{EXTRA_FRAG_PARAMS}}) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        {{FORWARD_FRAGMENT_BODY}}
        
        {
            // Hook: alpha clipping
            {{ALPHA_CLIP_CALL}}
            
            // LOD crossfade support
            #ifdef LOD_FADE_CROSSFADE
                LODFadeCrossFade(input.{{SV_POSITION}});
            #endif
            
            return float4(CalcNdcMotionVectorFromCsPositions(input.curPositionCS, input.prevPositionCS), 0, 0);
        }
    }
    ENDHLSL
}