// =====================================================================
// OUTLINE PASS (Auto-generated by FreeSkies)
// =====================================================================
Pass
{
    Name "Outline"
    Tags { "LightMode" = "SRPDefaultUnlit" }
    ZWrite On
    ZTest LEqual
    Cull Front

    HLSLPROGRAM
    #pragma target 4.5
    {{TESSELLATION_PRAGMAS}}
    {{VERTEX_PRAGMA}}
    #pragma fragment OutlineFragment
    
    #pragma multi_compile_instancing
    #pragma multi_compile _ DOTS_INSTANCING_ON
    #pragma shader_feature_local _ENABLE_OUTLINES
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}

    // -------------------------------------------------------------------------
    // Shared body from MainPass
    // -------------------------------------------------------------------------
    {{FORWARD_CONTENT}}    

    
    // -------------------------------------------------------------------------
    // Hook Functions
    // -------------------------------------------------------------------------
    {{HOOK_DEFINES}}
    {{HOOK_FUNCTIONS}}
    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    OutlineInterpolators OutlineVertex(OutlineAttributes input)
    {
        OutlineInterpolators output = (OutlineInterpolators)0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        // Hook: vertex displacement
        {{VERTEX_DISPLACEMENT_CALL}}
        
        // Expand along normal for outline effect
        #ifdef _ENABLE_OUTLINES
        input.{{POSITION}}.xyz += input.{{NORMAL}} * _OutlineWidth * 0.01;
        #endif
        
        output.{{SV_POSITION}} = TransformObjectToHClip(input.{{POSITION}}.xyz);
        
        return output;
    }

    // -------------------------------------------------------------------------
    // Tessellation
    // -------------------------------------------------------------------------
    {{TESSELLATION_CODE}}
    
    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 OutlineFragment(OutlineInterpolators input) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        #ifdef _ENABLE_OUTLINES
        return _OutlineColor;
        #else
        discard;
        return 0;
        #endif
    }
    ENDHLSL
}
