// =====================================================================
// SHADOW CASTER PASS (Auto-generated by FreeSkies)
// =====================================================================
Pass
{
    Name "ShadowCaster"
    Tags { "LightMode" = "ShadowCaster" }
    ZWrite On
    ZTest LEqual
    ColorMask 0
    Cull Back

    HLSLPROGRAM
    #pragma target 4.5
    {{TESSELLATION_PRAGMAS}}
    {{VERTEX_PRAGMA}}
    #pragma fragment ShadowCasterFragment
    
    #pragma multi_compile_instancing
    #pragma multi_compile _ DOTS_INSTANCING_ON
    #pragma multi_compile_vertex _ _CASTING_PUNCTUAL_LIGHT_SHADOW
    
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
    #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"
    
    {{FORWARD_CONTENT}}
    
    // -------------------------------------------------------------------------
    // Material Data
    // -------------------------------------------------------------------------
    {{CBUFFER}}
    {{TEXTURES}}
    
    // Shadow-specific uniforms
    float3 _LightDirection;
    float3 _LightPosition;
    
    // -------------------------------------------------------------------------
    // Structs
    // -------------------------------------------------------------------------
    {{ATTRIBUTES_STRUCT}}
    {{INTERPOLATORS_STRUCT}}
    
    // -------------------------------------------------------------------------
    // Hook Functions
    // -------------------------------------------------------------------------
    {{HOOK_DEFINES}}
    {{HOOK_FUNCTIONS}}
    
    // -------------------------------------------------------------------------
    // Tessellation
    // -------------------------------------------------------------------------
    {{TESSELLATION_CODE}}
    
    // -------------------------------------------------------------------------
    // Vertex
    // -------------------------------------------------------------------------
    ShadowCasterInterpolators ShadowCasterVertex(ShadowCasterAttributes input)
    {
        ShadowCasterInterpolators output = (ShadowCasterInterpolators)0;
        
        UNITY_SETUP_INSTANCE_ID(input);
        UNITY_TRANSFER_INSTANCE_ID(input, output);
        
        // Hook: vertex displacement
        {{VERTEX_DISPLACEMENT_CALL}}
        
        // Calculate shadow-biased position
        float3 positionWS = TransformObjectToWorld(input.{{POSITION}}.xyz);
        float3 normalWS = TransformObjectToWorldNormal(input.{{NORMAL}});
        
        #if _CASTING_PUNCTUAL_LIGHT_SHADOW
            float3 lightDirectionWS = normalize(_LightPosition - positionWS);
        #else
            float3 lightDirectionWS = _LightDirection;
        #endif
        
        output.{{SV_POSITION}} = TransformWorldToHClip(ApplyShadowBias(positionWS, normalWS, lightDirectionWS));
        
        // Transfer UV for alpha clip
        output.{{TEXCOORD0}} = input.{{TEXCOORD0}};
        
        // Hook: transfer extra interpolators
        {{INTERPOLATOR_TRANSFER_CALL}}
        
        return output;
    }

    // -------------------------------------------------------------------------
    // Fragment
    // -------------------------------------------------------------------------
    half4 ShadowCasterFragment(ShadowCasterInterpolators input) : SV_TARGET
    {
        UNITY_SETUP_INSTANCE_ID(input);
        
        // Hook: alpha clipping
        {{ALPHA_CLIP_CALL}}
        
        return 0;
    }
    ENDHLSL
}
