// =============================================================================
// TESSELLATION (Auto-generated by ShaderGen)
// =============================================================================

// Tessellation keywords
#pragma shader_feature_local _TESSELLATION
#pragma shader_feature_local _ TESS_MODE_UNIFORM TESS_MODE_EDGE_LENGTH TESS_MODE_DISTANCE TESS_MODE_EDGE_DISTANCE
#pragma shader_feature_local _ TESS_PHONG
#pragma shader_feature_local _ TESS_FRUSTUM_CULL
#pragma shader_feature_local _ TESS_BACKFACE_CULL

// Tessellation stage pragmas (always present)
#pragma require tessellation tessHW
#pragma hull Hull
#pragma domain Domain

{{HOOK_DEFINES}}

#ifdef _TESSELLATION

// Default mode if none specified
#if !defined(TESS_MODE_UNIFORM) && !defined(TESS_MODE_EDGE_LENGTH) && !defined(TESS_MODE_DISTANCE) && !defined(TESS_MODE_EDGE_DISTANCE)
    #define TESS_MODE_DISTANCE
#endif

#ifndef TESS_MAX_FACTOR
    #define TESS_MAX_FACTOR 64.0
#endif

#ifndef TESS_MIN_FACTOR
    #define TESS_MIN_FACTOR 1.0
#endif

// -----------------------------------------------------------------------------
// Structures
// -----------------------------------------------------------------------------

struct TessControlPoint
{
{{TESS_CONTROL_POINT_FIELDS}}
    #ifdef FS_TESSELLATION_FACTOR_OVERRIDE
    float _tessFactorOverride : TEXCOORD7;
    #endif
    UNITY_VERTEX_INPUT_INSTANCE_ID
};

struct TessFactors
{
    float edge[3] : SV_TessFactor;
    float inside : SV_InsideTessFactor;
    
    #ifdef TESS_PHONG
        float3 n0 : NORMAL0;
        float3 n1 : NORMAL1;
        float3 n2 : NORMAL2;
    #endif
};

// -----------------------------------------------------------------------------
// Factor Calculations
// -----------------------------------------------------------------------------

float CalcEdgeFactor(float3 p0WS, float3 p1WS)
{
    float3 center = (p0WS + p1WS) * 0.5;
    float edgeLen = distance(p0WS, p1WS);
    float4 clip = TransformWorldToHClip(center);
    float screenSize = edgeLen * _ScreenParams.y / (_TessellationEdgeLength * clip.w);
    return clamp(screenSize, TESS_MIN_FACTOR, _TessellationFactor);
}

float CalcDistanceFactor(float3 posWS)
{
    float dist = distance(_WorldSpaceCameraPos, posWS);
    float t = saturate((dist - _TessellationMinDist) / (_TessellationMaxDist - _TessellationMinDist));
    return lerp(_TessellationFactor, TESS_MIN_FACTOR, t);
}

float CalcEdgeDistanceFactor(float3 p0WS, float3 p1WS)
{
    float3 center = (p0WS + p1WS) * 0.5;
    float edge = CalcEdgeFactor(p0WS, p1WS);
    float dist = CalcDistanceFactor(center) / _TessellationFactor;
    return edge * dist;
}

// -----------------------------------------------------------------------------
// Culling
// -----------------------------------------------------------------------------

#ifdef TESS_FRUSTUM_CULL
bool FrustumCull(float3 p0, float3 p1, float3 p2)
{
    float3 minB = min(min(p0, p1), p2);
    float3 maxB = max(max(p0, p1), p2);
    
    [unroll]
    for (int i = 0; i < 6; i++)
    {
        float4 plane = unity_CameraWorldClipPlanes[i];
        float3 n = plane.xyz;
        float3 corner = float3(
            n.x >= 0 ? maxB.x : minB.x,
            n.y >= 0 ? maxB.y : minB.y,
            n.z >= 0 ? maxB.z : minB.z
        );
        if (dot(n, corner) + plane.w < 0) return true;
    }
    return false;
}
#endif

#ifdef TESS_BACKFACE_CULL
bool BackfaceCull(float3 p0, float3 p1, float3 p2)
{
    float3 center = (p0 + p1 + p2) / 3.0;
    float3 view = normalize(_WorldSpaceCameraPos - center);
    float3 normal = normalize(cross(p1 - p0, p2 - p0));
    return dot(view, normal) < -0.1;
}
#endif

// -----------------------------------------------------------------------------
// Vertex (Pass-through to control point)
// -----------------------------------------------------------------------------

TessControlPoint TessVertex({{ATTRIBUTES_NAME}} input)
{
    TessControlPoint o = (TessControlPoint)0;
    
    UNITY_SETUP_INSTANCE_ID(input);
    UNITY_TRANSFER_INSTANCE_ID(input, o);
    
{{TESS_VERTEX_BODY}}

    #ifdef FS_TESSELLATION_FACTOR_OVERRIDE
    float _overrideFactor = _TessellationFactor;
    {{TESSELLATION_FACTOR_OVERRIDE_CALL}}
    o._tessFactorOverride = _overrideFactor;
    #endif
    
    return o;
}

// -----------------------------------------------------------------------------
// Hull Shader
// -----------------------------------------------------------------------------

TessFactors PatchConstant(InputPatch<TessControlPoint, 3> patch)
{
    TessFactors f = (TessFactors)0;
    
    UNITY_SETUP_INSTANCE_ID(patch[0]);
    
    float3 p0 = TransformObjectToWorld(patch[0].positionOS.xyz);
    float3 p1 = TransformObjectToWorld(patch[1].positionOS.xyz);
    float3 p2 = TransformObjectToWorld(patch[2].positionOS.xyz);
    
    #ifdef TESS_FRUSTUM_CULL
        if (FrustumCull(p0, p1, p2))
        {
            f.edge[0] = f.edge[1] = f.edge[2] = f.inside = 0;
            return f;
        }
    #endif
    
    #ifdef TESS_BACKFACE_CULL
        if (BackfaceCull(p0, p1, p2))
        {
            f.edge[0] = f.edge[1] = f.edge[2] = f.inside = 0;
            return f;
        }
    #endif
    
    #if defined(TESS_MODE_UNIFORM)
        f.edge[0] = f.edge[1] = f.edge[2] = f.inside = _TessellationFactor;
        
    #elif defined(TESS_MODE_EDGE_LENGTH)
        f.edge[0] = CalcEdgeFactor(p1, p2);
        f.edge[1] = CalcEdgeFactor(p2, p0);
        f.edge[2] = CalcEdgeFactor(p0, p1);
        f.inside = (f.edge[0] + f.edge[1] + f.edge[2]) / 3.0;
        
    #elif defined(TESS_MODE_DISTANCE)
        f.edge[0] = CalcDistanceFactor((p1 + p2) * 0.5);
        f.edge[1] = CalcDistanceFactor((p2 + p0) * 0.5);
        f.edge[2] = CalcDistanceFactor((p0 + p1) * 0.5);
        f.inside = (f.edge[0] + f.edge[1] + f.edge[2]) / 3.0;
        
    #elif defined(TESS_MODE_EDGE_DISTANCE)
        f.edge[0] = CalcEdgeDistanceFactor(p1, p2);
        f.edge[1] = CalcEdgeDistanceFactor(p2, p0);
        f.edge[2] = CalcEdgeDistanceFactor(p0, p1);
        f.inside = (f.edge[0] + f.edge[1] + f.edge[2]) / 3.0;
    #endif
    
    #ifdef TESS_PHONG
        f.n0 = TransformObjectToWorldNormal(patch[0].normalOS);
        f.n1 = TransformObjectToWorldNormal(patch[1].normalOS);
        f.n2 = TransformObjectToWorldNormal(patch[2].normalOS);
    #endif
    
    #ifdef FS_TESSELLATION_FACTOR_OVERRIDE
    float _avgFactor = (patch[0]._tessFactorOverride + patch[1]._tessFactorOverride + patch[2]._tessFactorOverride) / 3.0;
    f.edge[0] = f.edge[1] = f.edge[2] = f.inside = _avgFactor;
    #endif
    
    return f;
}

[domain("tri")]
[outputcontrolpoints(3)]
[outputtopology("triangle_cw")]
[partitioning("fractional_odd")]
[patchconstantfunc("PatchConstant")]
TessControlPoint Hull(InputPatch<TessControlPoint, 3> patch, uint id : SV_OutputControlPointID)
{
    return patch[id];
}

// -----------------------------------------------------------------------------
// Domain Shader
// -----------------------------------------------------------------------------

[domain("tri")]
{{INTERPOLATORS_NAME}} Domain(TessFactors factors, OutputPatch<TessControlPoint, 3> patch, float3 bary : SV_DomainLocation)
{
    {{ATTRIBUTES_NAME}} input = ({{ATTRIBUTES_NAME}})0;
    
    UNITY_TRANSFER_INSTANCE_ID(patch[0], input);
    
    #define BARY_INTERP(field) (patch[0].field * bary.x + patch[1].field * bary.y + patch[2].field * bary.z)
    
{{DOMAIN_INTERPOLATION}}
    
    #ifdef TESS_PHONG
        float3 posWS = TransformObjectToWorld(input.positionOS.xyz);
        
        float3 cp0 = TransformObjectToWorld(patch[0].positionOS.xyz);
        float3 cp1 = TransformObjectToWorld(patch[1].positionOS.xyz);
        float3 cp2 = TransformObjectToWorld(patch[2].positionOS.xyz);
        
        float3 proj0 = posWS - dot(posWS - cp0, factors.n0) * factors.n0;
        float3 proj1 = posWS - dot(posWS - cp1, factors.n1) * factors.n1;
        float3 proj2 = posWS - dot(posWS - cp2, factors.n2) * factors.n2;
        
        float3 phongPos = proj0 * bary.x + proj1 * bary.y + proj2 * bary.z;
        posWS = lerp(posWS, phongPos, _PhongStrength);
        
        input.positionOS = float4(TransformWorldToObject(posWS), 1);
    #endif
    
    #undef BARY_INTERP
    
    return {{VERTEX_FUNCTION}}(input);
}

#else // !_TESSELLATION

// -----------------------------------------------------------------------------
// Passthrough when tessellation disabled
// -----------------------------------------------------------------------------

struct TessControlPoint
{
{{TESS_CONTROL_POINT_FIELDS}}
    UNITY_VERTEX_INPUT_INSTANCE_ID
};

struct TessFactors
{
    float edge[3] : SV_TessFactor;
    float inside : SV_InsideTessFactor;
};

TessControlPoint TessVertex({{ATTRIBUTES_NAME}} input)
{
    TessControlPoint o = (TessControlPoint)0;
    UNITY_SETUP_INSTANCE_ID(input);
    UNITY_TRANSFER_INSTANCE_ID(input, o);
{{TESS_VERTEX_BODY}}
    return o;
}

TessFactors PatchConstant(InputPatch<TessControlPoint, 3> patch)
{
    TessFactors f;
    f.edge[0] = f.edge[1] = f.edge[2] = 1;
    f.inside = 1;
    return f;
}

[domain("tri")]
[outputcontrolpoints(3)]
[outputtopology("triangle_cw")]
[partitioning("fractional_odd")]
[patchconstantfunc("PatchConstant")]
TessControlPoint Hull(InputPatch<TessControlPoint, 3> patch, uint id : SV_OutputControlPointID)
{
    return patch[id];
}

[domain("tri")]
{{INTERPOLATORS_NAME}} Domain(TessFactors factors, OutputPatch<TessControlPoint, 3> patch, float3 bary : SV_DomainLocation)
{
    {{ATTRIBUTES_NAME}} input = ({{ATTRIBUTES_NAME}})0;
    UNITY_TRANSFER_INSTANCE_ID(patch[0], input);
    
{{DOMAIN_INTERPOLATION_PASSTHROUGH}}
    
    return {{VERTEX_FUNCTION}}(input);
}

#endif // _TESSELLATION
